name: Workflow for Codecov

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.7.1"

      - uses: actions/cache@v4
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - run: poetry install
      - run: poetry run python -m pytest --cov-report json:cov.json --cov test
        env:
          GH_PAT_PERSONAL: ${{ secrets.GH_PAT_PERSONAL }}
          GH_PAT_ORGANIZATION: ${{ secrets.GH_PAT_ORGANIZATION }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4        
        with:
          files: /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/cov.json
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
